version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: schedule
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    volumes:
      - .:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db:
